/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'
import { Route as AuthenticatedAdsIndexRouteImport } from './routes/_authenticated/ads.index'
import { Route as AuthenticatedAdsSaudeRouteImport } from './routes/_authenticated/ads.saude'
import { Route as AuthenticatedAdsRotinasRouteImport } from './routes/_authenticated/ads.rotinas'
import { Route as AuthenticatedAdsLpsRouteImport } from './routes/_authenticated/ads.lps'
import { Route as AuthenticatedAdsAnunciosRouteImport } from './routes/_authenticated/ads.anuncios'
import { Route as AuthenticatedAdsCampanhasIndexRouteImport } from './routes/_authenticated/ads.campanhas.index'
import { Route as AuthenticatedAdsCampanhasNovaRouteImport } from './routes/_authenticated/ads.campanhas.nova'
import { Route as AuthenticatedAdsCampanhasIdRouteImport } from './routes/_authenticated/ads.campanhas.$id'
import { Route as AuthenticatedAdsCampanhasIdAdicionarAdsetRouteImport } from './routes/_authenticated/ads.campanhas.$id.adicionar-adset'
import { Route as AuthenticatedAdsAdsetsIdAdicionarAdRouteImport } from './routes/_authenticated/ads.adsets.$id.adicionar-ad'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdsIndexRoute = AuthenticatedAdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdsRoute,
} as any)
const AuthenticatedAdsSaudeRoute = AuthenticatedAdsSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedAdsRoute,
} as any)
const AuthenticatedAdsRotinasRoute = AuthenticatedAdsRotinasRouteImport.update({
  id: '/rotinas',
  path: '/rotinas',
  getParentRoute: () => AuthenticatedAdsRoute,
} as any)
const AuthenticatedAdsLpsRoute = AuthenticatedAdsLpsRouteImport.update({
  id: '/lps',
  path: '/lps',
  getParentRoute: () => AuthenticatedAdsRoute,
} as any)
const AuthenticatedAdsAnunciosRoute =
  AuthenticatedAdsAnunciosRouteImport.update({
    id: '/anuncios',
    path: '/anuncios',
    getParentRoute: () => AuthenticatedAdsRoute,
  } as any)
const AuthenticatedAdsCampanhasIndexRoute =
  AuthenticatedAdsCampanhasIndexRouteImport.update({
    id: '/campanhas/',
    path: '/campanhas/',
    getParentRoute: () => AuthenticatedAdsRoute,
  } as any)
const AuthenticatedAdsCampanhasNovaRoute =
  AuthenticatedAdsCampanhasNovaRouteImport.update({
    id: '/campanhas/nova',
    path: '/campanhas/nova',
    getParentRoute: () => AuthenticatedAdsRoute,
  } as any)
const AuthenticatedAdsCampanhasIdRoute =
  AuthenticatedAdsCampanhasIdRouteImport.update({
    id: '/campanhas/$id',
    path: '/campanhas/$id',
    getParentRoute: () => AuthenticatedAdsRoute,
  } as any)
const AuthenticatedAdsCampanhasIdAdicionarAdsetRoute =
  AuthenticatedAdsCampanhasIdAdicionarAdsetRouteImport.update({
    id: '/adicionar-adset',
    path: '/adicionar-adset',
    getParentRoute: () => AuthenticatedAdsCampanhasIdRoute,
  } as any)
const AuthenticatedAdsAdsetsIdAdicionarAdRoute =
  AuthenticatedAdsAdsetsIdAdicionarAdRouteImport.update({
    id: '/adsets/$id/adicionar-ad',
    path: '/adsets/$id/adicionar-ad',
    getParentRoute: () => AuthenticatedAdsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ads': typeof AuthenticatedAdsRouteWithChildren
  '/ads/anuncios': typeof AuthenticatedAdsAnunciosRoute
  '/ads/lps': typeof AuthenticatedAdsLpsRoute
  '/ads/rotinas': typeof AuthenticatedAdsRotinasRoute
  '/ads/saude': typeof AuthenticatedAdsSaudeRoute
  '/ads/': typeof AuthenticatedAdsIndexRoute
  '/ads/campanhas/$id': typeof AuthenticatedAdsCampanhasIdRouteWithChildren
  '/ads/campanhas/nova': typeof AuthenticatedAdsCampanhasNovaRoute
  '/ads/campanhas/': typeof AuthenticatedAdsCampanhasIndexRoute
  '/ads/adsets/$id/adicionar-ad': typeof AuthenticatedAdsAdsetsIdAdicionarAdRoute
  '/ads/campanhas/$id/adicionar-adset': typeof AuthenticatedAdsCampanhasIdAdicionarAdsetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ads/anuncios': typeof AuthenticatedAdsAnunciosRoute
  '/ads/lps': typeof AuthenticatedAdsLpsRoute
  '/ads/rotinas': typeof AuthenticatedAdsRotinasRoute
  '/ads/saude': typeof AuthenticatedAdsSaudeRoute
  '/ads': typeof AuthenticatedAdsIndexRoute
  '/ads/campanhas/$id': typeof AuthenticatedAdsCampanhasIdRouteWithChildren
  '/ads/campanhas/nova': typeof AuthenticatedAdsCampanhasNovaRoute
  '/ads/campanhas': typeof AuthenticatedAdsCampanhasIndexRoute
  '/ads/adsets/$id/adicionar-ad': typeof AuthenticatedAdsAdsetsIdAdicionarAdRoute
  '/ads/campanhas/$id/adicionar-adset': typeof AuthenticatedAdsCampanhasIdAdicionarAdsetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ads': typeof AuthenticatedAdsRouteWithChildren
  '/_authenticated/ads/anuncios': typeof AuthenticatedAdsAnunciosRoute
  '/_authenticated/ads/lps': typeof AuthenticatedAdsLpsRoute
  '/_authenticated/ads/rotinas': typeof AuthenticatedAdsRotinasRoute
  '/_authenticated/ads/saude': typeof AuthenticatedAdsSaudeRoute
  '/_authenticated/ads/': typeof AuthenticatedAdsIndexRoute
  '/_authenticated/ads/campanhas/$id': typeof AuthenticatedAdsCampanhasIdRouteWithChildren
  '/_authenticated/ads/campanhas/nova': typeof AuthenticatedAdsCampanhasNovaRoute
  '/_authenticated/ads/campanhas/': typeof AuthenticatedAdsCampanhasIndexRoute
  '/_authenticated/ads/adsets/$id/adicionar-ad': typeof AuthenticatedAdsAdsetsIdAdicionarAdRoute
  '/_authenticated/ads/campanhas/$id/adicionar-adset': typeof AuthenticatedAdsCampanhasIdAdicionarAdsetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ads'
    | '/ads/anuncios'
    | '/ads/lps'
    | '/ads/rotinas'
    | '/ads/saude'
    | '/ads/'
    | '/ads/campanhas/$id'
    | '/ads/campanhas/nova'
    | '/ads/campanhas/'
    | '/ads/adsets/$id/adicionar-ad'
    | '/ads/campanhas/$id/adicionar-adset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ads/anuncios'
    | '/ads/lps'
    | '/ads/rotinas'
    | '/ads/saude'
    | '/ads'
    | '/ads/campanhas/$id'
    | '/ads/campanhas/nova'
    | '/ads/campanhas'
    | '/ads/adsets/$id/adicionar-ad'
    | '/ads/campanhas/$id/adicionar-adset'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ads'
    | '/_authenticated/ads/anuncios'
    | '/_authenticated/ads/lps'
    | '/_authenticated/ads/rotinas'
    | '/_authenticated/ads/saude'
    | '/_authenticated/ads/'
    | '/_authenticated/ads/campanhas/$id'
    | '/_authenticated/ads/campanhas/nova'
    | '/_authenticated/ads/campanhas/'
    | '/_authenticated/ads/adsets/$id/adicionar-ad'
    | '/_authenticated/ads/campanhas/$id/adicionar-adset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads/': {
      id: '/_authenticated/ads/'
      path: '/'
      fullPath: '/ads/'
      preLoaderRoute: typeof AuthenticatedAdsIndexRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/_authenticated/ads/saude': {
      id: '/_authenticated/ads/saude'
      path: '/saude'
      fullPath: '/ads/saude'
      preLoaderRoute: typeof AuthenticatedAdsSaudeRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/_authenticated/ads/rotinas': {
      id: '/_authenticated/ads/rotinas'
      path: '/rotinas'
      fullPath: '/ads/rotinas'
      preLoaderRoute: typeof AuthenticatedAdsRotinasRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/_authenticated/ads/lps': {
      id: '/_authenticated/ads/lps'
      path: '/lps'
      fullPath: '/ads/lps'
      preLoaderRoute: typeof AuthenticatedAdsLpsRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/_authenticated/ads/anuncios': {
      id: '/_authenticated/ads/anuncios'
      path: '/anuncios'
      fullPath: '/ads/anuncios'
      preLoaderRoute: typeof AuthenticatedAdsAnunciosRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/_authenticated/ads/campanhas/': {
      id: '/_authenticated/ads/campanhas/'
      path: '/campanhas'
      fullPath: '/ads/campanhas/'
      preLoaderRoute: typeof AuthenticatedAdsCampanhasIndexRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/_authenticated/ads/campanhas/nova': {
      id: '/_authenticated/ads/campanhas/nova'
      path: '/campanhas/nova'
      fullPath: '/ads/campanhas/nova'
      preLoaderRoute: typeof AuthenticatedAdsCampanhasNovaRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/_authenticated/ads/campanhas/$id': {
      id: '/_authenticated/ads/campanhas/$id'
      path: '/campanhas/$id'
      fullPath: '/ads/campanhas/$id'
      preLoaderRoute: typeof AuthenticatedAdsCampanhasIdRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/_authenticated/ads/campanhas/$id/adicionar-adset': {
      id: '/_authenticated/ads/campanhas/$id/adicionar-adset'
      path: '/adicionar-adset'
      fullPath: '/ads/campanhas/$id/adicionar-adset'
      preLoaderRoute: typeof AuthenticatedAdsCampanhasIdAdicionarAdsetRouteImport
      parentRoute: typeof AuthenticatedAdsCampanhasIdRoute
    }
    '/_authenticated/ads/adsets/$id/adicionar-ad': {
      id: '/_authenticated/ads/adsets/$id/adicionar-ad'
      path: '/adsets/$id/adicionar-ad'
      fullPath: '/ads/adsets/$id/adicionar-ad'
      preLoaderRoute: typeof AuthenticatedAdsAdsetsIdAdicionarAdRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
  }
}

interface AuthenticatedAdsCampanhasIdRouteChildren {
  AuthenticatedAdsCampanhasIdAdicionarAdsetRoute: typeof AuthenticatedAdsCampanhasIdAdicionarAdsetRoute
}

const AuthenticatedAdsCampanhasIdRouteChildren: AuthenticatedAdsCampanhasIdRouteChildren =
  {
    AuthenticatedAdsCampanhasIdAdicionarAdsetRoute:
      AuthenticatedAdsCampanhasIdAdicionarAdsetRoute,
  }

const AuthenticatedAdsCampanhasIdRouteWithChildren =
  AuthenticatedAdsCampanhasIdRoute._addFileChildren(
    AuthenticatedAdsCampanhasIdRouteChildren,
  )

interface AuthenticatedAdsRouteChildren {
  AuthenticatedAdsAnunciosRoute: typeof AuthenticatedAdsAnunciosRoute
  AuthenticatedAdsLpsRoute: typeof AuthenticatedAdsLpsRoute
  AuthenticatedAdsRotinasRoute: typeof AuthenticatedAdsRotinasRoute
  AuthenticatedAdsSaudeRoute: typeof AuthenticatedAdsSaudeRoute
  AuthenticatedAdsIndexRoute: typeof AuthenticatedAdsIndexRoute
  AuthenticatedAdsCampanhasIdRoute: typeof AuthenticatedAdsCampanhasIdRouteWithChildren
  AuthenticatedAdsCampanhasNovaRoute: typeof AuthenticatedAdsCampanhasNovaRoute
  AuthenticatedAdsCampanhasIndexRoute: typeof AuthenticatedAdsCampanhasIndexRoute
  AuthenticatedAdsAdsetsIdAdicionarAdRoute: typeof AuthenticatedAdsAdsetsIdAdicionarAdRoute
}

const AuthenticatedAdsRouteChildren: AuthenticatedAdsRouteChildren = {
  AuthenticatedAdsAnunciosRoute: AuthenticatedAdsAnunciosRoute,
  AuthenticatedAdsLpsRoute: AuthenticatedAdsLpsRoute,
  AuthenticatedAdsRotinasRoute: AuthenticatedAdsRotinasRoute,
  AuthenticatedAdsSaudeRoute: AuthenticatedAdsSaudeRoute,
  AuthenticatedAdsIndexRoute: AuthenticatedAdsIndexRoute,
  AuthenticatedAdsCampanhasIdRoute:
    AuthenticatedAdsCampanhasIdRouteWithChildren,
  AuthenticatedAdsCampanhasNovaRoute: AuthenticatedAdsCampanhasNovaRoute,
  AuthenticatedAdsCampanhasIndexRoute: AuthenticatedAdsCampanhasIndexRoute,
  AuthenticatedAdsAdsetsIdAdicionarAdRoute:
    AuthenticatedAdsAdsetsIdAdicionarAdRoute,
}

const AuthenticatedAdsRouteWithChildren =
  AuthenticatedAdsRoute._addFileChildren(AuthenticatedAdsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdsRoute: AuthenticatedAdsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
